# ***Image Classification Model using YOLO (You Only Look Once)***

<table class="tfo-notebook-buttons" align="left">
  <td>
    <a target="_blank" href="https://pjreddie.com/darknet/yolo/"><img src="https://pjreddie.com/media/image/yologo_2.png" alt="Yolo" width="80" height="40" />View on Yolo site</a>
  </td>
  <td>
    <a target="_blank" href="https://github.com/imvickykumar999/YOLO-Image-detection/blob/master/YOLO.ipynb"><img src="https://www.tensorflow.org/images/colab_logo_32px.png" />Run in Google Colab</a>
  </td>
  <td>
    <a target="_blank" href="https://github.com/imvickykumar999/YOLO-Image-detection"><img src="https://www.tensorflow.org/images/GitHub-Mark-32px.png" />View source on GitHub</a>
  </td>
  <td>
    <a href="https://pjreddie.com/media/files/yolov3.weights"><img src="https://www.tensorflow.org/images/download_logo_32px.png" />Download Yolo Weights</a>
  </td>
</table>

In [ ]:
!git clone https://github.com/pjreddie/darknet

Cloning into 'darknet'...
remote: Enumerating objects: 5910, done.
remote: Total 5910 (delta 0), reused 0 (delta 0), pack-reused 5910
Receiving objects: 100% (5910/5910), 6.33 MiB | 22.21 MiB/s, done.
Resolving deltas: 100% (3917/3917), done.


In [ ]:
cd darknet

/content/darknet


In [ ]:
!make

mkdir -p obj
mkdir -p backup
mkdir -p results
gcc -Iinclude/ -Isrc/ -Wall -Wno-unused-result -Wno-unknown-pragmas -Wfatal-errors -fPIC -Ofast -c ./src/gemm.c -o obj/gemm.o
gcc -Iinclude/ -Isrc/ -Wall -Wno-unused-result -Wno-unknown-pragmas -Wfatal-errors -fPIC -Ofast -c ./src/utils.c -o obj/utils.o
gcc -Iinclude/ -Isrc/ -Wall -Wno-unused-result -Wno-unknown-pragmas -Wfatal-errors -fPIC -Ofast -c ./src/cuda.c -o obj/cuda.o
gcc -Iinclude/ -Isrc/ -Wall -Wno-unused-result -Wno-unknown-pragmas -Wfatal-errors -fPIC -Ofast -c ./src/deconvolutional_layer.c -o obj/deconvolutional_layer.o
gcc -Iinclude/ -Isrc/ -Wall -Wno-unused-result -Wno-unknown-pragmas -Wfatal-errors -fPIC -Ofast -c ./src/convolutional_layer.c -o obj/convolutional_layer.o
gcc -Iinclude/ -Isrc/ -Wall -Wno-unused-result -Wno-unknown-pragmas -Wfatal-errors -fPIC -Ofast -c ./src/list.c -o obj/list.o
gcc -Iinclude/ -Isrc/ -Wall -Wno-unused-result -Wno-unknown-pragmas -Wfatal-errors -fPIC -Ofast -c ./src/image.c -o obj/image.o
gcc 

In [ ]:
!wget https://pjreddie.com/media/files/yolov3.weights

--2020-08-13 06:44:29--  https://pjreddie.com/media/files/yolov3.weights
Resolving pjreddie.com (pjreddie.com)... 128.208.4.108
Connecting to pjreddie.com (pjreddie.com)|128.208.4.108|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 248007048 (237M) [application/octet-stream]
Saving to: ‘yolov3.weights’

yolov3.weights      100%[===================>] 236.52M   399KB/s    in 9m 8s   

2020-08-13 06:53:39 (442 KB/s) - ‘yolov3.weights’ saved [248007048/248007048]



In [ ]:
!./darknet detect cfg/yolov3.cfg yolov3.weights data/dog.jpg

layer     filters    size              input                output
    0 conv     32  3 x 3 / 1   608 x 608 x   3   ->   608 x 608 x  32  0.639 BFLOPs
    1 conv     64  3 x 3 / 2   608 x 608 x  32   ->   304 x 304 x  64  3.407 BFLOPs
    2 conv     32  1 x 1 / 1   304 x 304 x  64   ->   304 x 304 x  32  0.379 BFLOPs
    3 conv     64  3 x 3 / 1   304 x 304 x  32   ->   304 x 304 x  64  3.407 BFLOPs
    4 res    1                 304 x 304 x  64   ->   304 x 304 x  64
    5 conv    128  3 x 3 / 2   304 x 304 x  64   ->   152 x 152 x 128  3.407 BFLOPs
    6 conv     64  1 x 1 / 1   152 x 152 x 128   ->   152 x 152 x  64  0.379 BFLOPs
    7 conv    128  3 x 3 / 1   152 x 152 x  64   ->   152 x 152 x 128  3.407 BFLOPs
    8 res    5                 152 x 152 x 128   ->   152 x 152 x 128
    9 conv     64  1 x 1 / 1   152 x 152 x 128   ->   152 x 152 x  64  0.379 BFLOPs
   10 conv    128  3 x 3 / 1   152 x 152 x  64   ->   152 x 152 x 128  3.407 BFLOPs
   11 res    8                 152 x 

In [ ]:
!./darknet detector test cfg/coco.data cfg/yolov3.cfg yolov3.weights data/dog.jpg

layer     filters    size              input                output
    0 conv     32  3 x 3 / 1   608 x 608 x   3   ->   608 x 608 x  32  0.639 BFLOPs
    1 conv     64  3 x 3 / 2   608 x 608 x  32   ->   304 x 304 x  64  3.407 BFLOPs
    2 conv     32  1 x 1 / 1   304 x 304 x  64   ->   304 x 304 x  32  0.379 BFLOPs
    3 conv     64  3 x 3 / 1   304 x 304 x  32   ->   304 x 304 x  64  3.407 BFLOPs
    4 res    1                 304 x 304 x  64   ->   304 x 304 x  64
    5 conv    128  3 x 3 / 2   304 x 304 x  64   ->   152 x 152 x 128  3.407 BFLOPs
    6 conv     64  1 x 1 / 1   152 x 152 x 128   ->   152 x 152 x  64  0.379 BFLOPs
    7 conv    128  3 x 3 / 1   152 x 152 x  64   ->   152 x 152 x 128  3.407 BFLOPs
    8 res    5                 152 x 152 x 128   ->   152 x 152 x 128
    9 conv     64  1 x 1 / 1   152 x 152 x 128   ->   152 x 152 x  64  0.379 BFLOPs
   10 conv    128  3 x 3 / 1   152 x 152 x  64   ->   152 x 152 x 128  3.407 BFLOPs
   11 res    8                 152 x 

In [4]:
# !wget https://pjreddie.com/media/files/yolov3-tiny.weights

In [9]:
import numpy as np
import cv2

confidenceThreshold = 0.5
NMSThreshold = 0.3

modelConfiguration = r'C:\Users\Vicky Kumar\Desktop\Program Output\YOLO\yolov3.cfg'
modelWeights = r'C:\Users\Vicky Kumar\Desktop\Program Output\YOLO\yolov3.weights'
inputimage = r'C:\Users\Vicky Kumar\Desktop\Program Output\YOLO\person.jpg'
labelsPath = r'C:\Users\Vicky Kumar\Desktop\Program Output\YOLO\coco.names'


In [10]:
labels = open(labelsPath).read().strip().split('\n')
labels

['person',
 'bicycle',
 'car',
 'motorbike',
 'aeroplane',
 'bus',
 'train',
 'truck',
 'boat',
 'traffic light',
 'fire hydrant',
 'stop sign',
 'parking meter',
 'bench',
 'bird',
 'cat',
 'dog',
 'horse',
 'sheep',
 'cow',
 'elephant',
 'bear',
 'zebra',
 'giraffe',
 'backpack',
 'umbrella',
 'handbag',
 'tie',
 'suitcase',
 'frisbee',
 'skis',
 'snowboard',
 'sports ball',
 'kite',
 'baseball bat',
 'baseball glove',
 'skateboard',
 'surfboard',
 'tennis racket',
 'bottle',
 'wine glass',
 'cup',
 'fork',
 'knife',
 'spoon',
 'bowl',
 'banana',
 'apple',
 'sandwich',
 'orange',
 'broccoli',
 'carrot',
 'hot dog',
 'pizza',
 'donut',
 'cake',
 'chair',
 'sofa',
 'pottedplant',
 'bed',
 'diningtable',
 'toilet',
 'tvmonitor',
 'laptop',
 'mouse',
 'remote',
 'keyboard',
 'cell phone',
 'microwave',
 'oven',
 'toaster',
 'sink',
 'refrigerator',
 'book',
 'clock',
 'vase',
 'scissors',
 'teddy bear',
 'hair drier',
 'toothbrush']

In [11]:
s = np.random.seed(10)
type(s)

NoneType

In [12]:
COLORS = np.random.randint(0, 255, size=(len(labels), 3), dtype="uint8")
COLORS

array([[  9,  69, 117],
       [197, 125, 156],
       [123,  76, 228],
       [ 79,   5,  15],
       [114, 157, 126],
       [ 64, 197,  54],
       [162, 113, 109],
       [105, 113, 123],
       [156, 177, 191],
       [156,  36, 248],
       [212, 217,  39],
       [158, 127, 221],
       [146,  84, 149],
       [240,  69, 140],
       [ 57, 157, 167],
       [113,   6, 113],
       [ 63, 180,  50],
       [250, 167, 142],
       [181,   8,  36],
       [178, 194,  73],
       [ 36, 252,  67],
       [  0, 217,  74],
       [ 43, 234, 121],
       [123,  67,  40],
       [112, 157,  22],
       [246,  41, 127],
       [ 38, 164, 189],
       [115, 175, 115],
       [185,  14, 175],
       [ 16, 150,  17],
       [244, 100, 209],
       [ 12, 209, 239],
       [192,   2,   1],
       [139, 201,   8],
       [ 86,  54,   8],
       [ 31, 131,  88],
       [141,  12, 228],
       [107, 237,   7],
       [208, 122,  28],
       [184,  50,  62],
       [130, 206, 156],
       [ 33, 126

In [17]:
net = cv2.dnn.readNetFromDarknet(modelConfiguration, modelWeights)
net, net.getUnconnectedOutLayers()

(<dnn_Net 000002B260FE6DD0>,
 array([[200],
        [227],
        [254]], dtype=int32))

In [14]:
image = cv2.imread(inputimage)
type(image)

numpy.ndarray

In [15]:
(H, W) = image.shape[:2]
layerName = net.getLayerNames()
layerName

['conv_0',
 'bn_0',
 'relu_0',
 'conv_1',
 'bn_1',
 'relu_1',
 'conv_2',
 'bn_2',
 'relu_2',
 'conv_3',
 'bn_3',
 'relu_3',
 'shortcut_4',
 'conv_5',
 'bn_5',
 'relu_5',
 'conv_6',
 'bn_6',
 'relu_6',
 'conv_7',
 'bn_7',
 'relu_7',
 'shortcut_8',
 'conv_9',
 'bn_9',
 'relu_9',
 'conv_10',
 'bn_10',
 'relu_10',
 'shortcut_11',
 'conv_12',
 'bn_12',
 'relu_12',
 'conv_13',
 'bn_13',
 'relu_13',
 'conv_14',
 'bn_14',
 'relu_14',
 'shortcut_15',
 'conv_16',
 'bn_16',
 'relu_16',
 'conv_17',
 'bn_17',
 'relu_17',
 'shortcut_18',
 'conv_19',
 'bn_19',
 'relu_19',
 'conv_20',
 'bn_20',
 'relu_20',
 'shortcut_21',
 'conv_22',
 'bn_22',
 'relu_22',
 'conv_23',
 'bn_23',
 'relu_23',
 'shortcut_24',
 'conv_25',
 'bn_25',
 'relu_25',
 'conv_26',
 'bn_26',
 'relu_26',
 'shortcut_27',
 'conv_28',
 'bn_28',
 'relu_28',
 'conv_29',
 'bn_29',
 'relu_29',
 'shortcut_30',
 'conv_31',
 'bn_31',
 'relu_31',
 'conv_32',
 'bn_32',
 'relu_32',
 'shortcut_33',
 'conv_34',
 'bn_34',
 'relu_34',
 'conv_35',
 'bn

In [16]:
layerName = [layerName[i[0] - 1] for i in net.getUnconnectedOutLayers()]
layerName

['yolo_82', 'yolo_94', 'yolo_106']

In [18]:
blob = cv2.dnn.blobFromImage(image, 1 / 255.0, (416, 416), swapRB = True, crop = False)
blob

array([[[[0.7490196 , 0.74509805, 0.74509805, ..., 0.74509805,
          0.74509805, 0.7490196 ],
         [0.74509805, 0.74509805, 0.7411765 , ..., 0.74509805,
          0.74509805, 0.74509805],
         [0.7411765 , 0.7411765 , 0.7372549 , ..., 0.7411765 ,
          0.7411765 , 0.74509805],
         ...,
         [0.73333335, 0.69803923, 0.7490196 , ..., 0.6117647 ,
          0.6039216 , 0.5294118 ],
         [0.7137255 , 0.73333335, 0.7411765 , ..., 0.6       ,
          0.54901963, 0.58431375],
         [0.7137255 , 0.69411767, 0.7294118 , ..., 0.69411767,
          0.6313726 , 0.654902  ]],

        [[0.7960785 , 0.79215693, 0.79215693, ..., 0.81568635,
          0.81568635, 0.8196079 ],
         [0.79215693, 0.79215693, 0.79215693, ..., 0.81568635,
          0.81568635, 0.81568635],
         [0.78823537, 0.78823537, 0.79215693, ..., 0.8117648 ,
          0.8117648 , 0.81568635],
         ...,
         [0.6431373 , 0.60784316, 0.6666667 , ..., 0.53333336,
          0.5254902 , 0.4

In [20]:
nb = net.setInput(blob)
type(nb)

NoneType

In [21]:
layersOutputs = net.forward(layerName)
layersOutputs

[array([[0.05131535, 0.03309029, 0.2759047 , ..., 0.        , 0.        ,
         0.        ],
        [0.05464744, 0.02950711, 0.24525252, ..., 0.        , 0.        ,
         0.        ],
        [0.05472972, 0.02670236, 0.96304834, ..., 0.        , 0.        ,
         0.        ],
        ...,
        [0.96150774, 0.9517923 , 0.39629126, ..., 0.        , 0.        ,
         0.        ],
        [0.966527  , 0.96668345, 0.30495265, ..., 0.        , 0.        ,
         0.        ],
        [0.9695191 , 0.9622637 , 0.83987004, ..., 0.        , 0.        ,
         0.        ]], dtype=float32),
 array([[0.02680638, 0.02536237, 0.06056315, ..., 0.        , 0.        ,
         0.        ],
        [0.01934024, 0.02673072, 0.21589468, ..., 0.        , 0.        ,
         0.        ],
        [0.02690339, 0.0193949 , 0.09875187, ..., 0.        , 0.        ,
         0.        ],
        ...,
        [0.9751284 , 0.9797051 , 0.05022141, ..., 0.        , 0.        ,
         0.        

In [23]:
boxes = []
confidences = []
classIDs = []

confidenceThreshold

0.5

In [25]:
for output in layersOutputs:
    for detection in output:
        scores = detection[5:]
#         print('scores : ', scores)
        classID = np.argmax(scores)
#         print('classID : ', classID)
        confidence = scores[classID]
#         print('confidence : ', confidence)
        
        if confidence > confidenceThreshold:
            box = detection[0:4] * np.array([W, H, W, H])
#             print('box : ', box)
            ib = (centerX, centerY,  width, height) = box.astype('int')
#             print('int box : ', ib)
            x = int(centerX - (width/2))
            y = int(centerY - (height/2))
#             print(x, y)
            boxes.append([x, y, int(width), int(height)])
            confidences.append(float(confidence))
            classIDs.append(classID)
            
boxes, confidences, classIDs

([[181, 94, 104, 280],
  [394, 137, 213, 206],
  [59, 261, 146, 89],
  [190, 94, 86, 284],
  [76, 262, 118, 86],
  [181, 94, 104, 280],
  [394, 137, 213, 206],
  [59, 261, 146, 89],
  [190, 94, 86, 284],
  [76, 262, 118, 86]],
 [0.9397530555725098,
  0.9977298378944397,
  0.9942077398300171,
  0.9999475479125977,
  0.8075437545776367,
  0.9397530555725098,
  0.9977298378944397,
  0.9942077398300171,
  0.9999475479125977,
  0.8075437545776367],
 [0, 17, 16, 0, 16, 0, 17, 16, 0, 16])

In [26]:
detectionNMS = cv2.dnn.NMSBoxes(boxes, confidences, confidenceThreshold, NMSThreshold)
detectionNMS

array([[3],
       [1],
       [2]], dtype=int32)

In [27]:
len(detectionNMS)

3

In [28]:
for i in detectionNMS.flatten():
    (x, y) = (boxes[i][0], boxes[i][1])
    (w, h) = (boxes[i][2], boxes[i][3])

    detected = labels[classIDs[i]]
    print(detected)

    color = [int(c) for c in COLORS[classIDs[i]]]
    cv2.rectangle(image, (x, y), (x + w, y + h), color, 2)
    text = '{}: {:.4f}'.format(labels[classIDs[i]], confidences[i])
    cv2.putText(image, text, (x, y - 5), cv2.FONT_HERSHEY_SIMPLEX, 0.5, color, 2)

person
horse
dog


In [29]:
cv2.imshow('Image', image)
cv2.waitKey(0)

-1